# Linear Algebra, Advanced Concepts
This note-book is devoted to teaching how to use python for advanced concepts in linear algebra. Step by step you see how to use different functions in python to do computation in linear algebra.

## 1 Singular value decompisition

Use svd from .linalg to perform singular value decompisition. Let

$A = \begin{bmatrix}
1 & 7 & 2\\
4 & 0 & 9\\
5 & 8 & 2
\end{bmatrix}$

We can create $A$ as follows:

In [45]:
import numpy as np
A = np.array([[1,7,2],[4,0,9],[5,8,2]])
print(A)


[[1 7 2]
 [4 0 9]
 [5 8 2]]


As you see the print function in python cannot print this 2D-array in a pretty format. To solve this issue, we can create following function for printing matrices.

In [46]:
def printArray(A):
    if A.ndim > 1:
        for matrix_row in A:
            s = ''
            for element in matrix_row:
               
                s = s + '\t' + str(element)
            print(s)
            
    elif A.ndim == 1:
        s = ''
        for element in A:
            s = s + '\t' + str(element)
        print(s)
    print('')

In [47]:
printArray(A)

	1	7	2
	4	0	9
	5	8	2



Singular value decompostion of $A$ is $A = U\Sigma V^T$
we can use svd() in .linalg to do singular value decomposition in python

In [48]:
(U,S,VT) = np.linalg.svd(A)
print('U = ')
printArray(U)
print('S = ')
printArray(S)
print('VT = ')
printArray(VT)

U = 
	0.4955490212302891	-0.36519550871464956	-0.788075762837781
	0.5233789676437401	0.8496460787338146	-0.06462195540546112
	0.6931851295187129	-0.38043893242792737	0.612176931047899

S = 
	12.967612725738011	8.398154610072645	2.3047818422993984

VT = 
	0.46693178362590376	0.6951413784026855	0.5465831807441089
	0.13469556070380387	-0.6667988719461702	0.7329640989148127
	0.8739747223842462	-0.2686219060384506	-0.40498204432993057



Note that S computed by svd only contains the sigular values of S which are the diagonal elements $\Sigma$. $\Sigma$ is computed as follows

In [49]:
Sigma = np.diag(S)
printArray(Sigma)

	12.967612725738011	0.0	0.0
	0.0	8.398154610072645	0.0
	0.0	0.0	2.3047818422993984



We can see that the singular value decompisition is computed correctly by following command. 

In [50]:
diff = A - np.matmul(U,np.matmul(Sigma,VT))
print(np.max(np.abs(diff)))

6.168200105464311e-15


Determinat of the matrix have the following relationship with its singular values.
$\text{det}(A) = \sigma_1\cdot\sigma_2\cdot\sigma_3 \ldots \sigma_n$. We can show this as follows:

In [51]:
det_A = np.linalg.det(A)
print('det(A) = ', det_A)
singular_values_multiplications = np.prod(S)
print('singular values multiplications = ', singular_values_multiplications)

det(A) =  250.9999999999999
singular values multiplications =  250.99999999999972


## 2 Eigen values and Eigen vectors

Eigenvalues and eigen vectors of $A$ are computed by $\text{eig()}$ function from .linalg

In [52]:
(l,V) = np.linalg.eig(A)
print('eigen values = ')
printArray(l)
print('eigen vectors = ')
printArray(V)

eigen values = 
	12.889603103961992	-2.7136575578172217	-7.1759455461447645

eigen vectors = 
	-0.4628165201727251	-0.8798030708949003	0.5577205496916918
	-0.5995421343373721	0.3885030095494413	-0.7518744720388498
	-0.6529548972244545	0.2738831283867805	0.3516142300133738



Determinat of the matrix have the following relationship with its eigen values.
$\text{det}(A) = \lambda_1\cdot\lambda_2\cdot\lambda_3 \ldots \lambda_n$. We can show this as follows:

In [53]:
det_A = np.linalg.det(A)
print('det(A) = ', det_A)
eigen_values_multiplications = np.prod(l)
print('eigen values multiplications = ',eigen_values_multiplications)

det(A) =  250.9999999999999
eigen values multiplications =  250.99999999999983


We can also shows that roots squares of eigenvalues of $A^TA$(we can denote it by $\lambda$) are equal to singular values of $A$ (denoted by $\sigma$). $i.e. \sigma = \sqrt{\lambda}$

In [54]:
ATA = np.matmul(A.T,A)
(l_ATA,V) = np.linalg.eig(ATA)
print('root square of lambdas = ')
printArray(np.sqrt(l_ATA))
print('sigmas = ')
printArray(S)

root square of lambdas = 
	12.967612725738018	2.3047818422993998	8.398154610072647

sigmas = 
	12.967612725738011	8.398154610072645	2.3047818422993984



## 3 Complex matrix and Hermitian

Matrix A can have complex entries. For example:

$A = \begin{bmatrix}
1 & i+1 & 0\\
i & 3 & -1\\
4 & 7 & 0
\end{bmatrix}$  

Hermitian of A is conjugate transpose of the matrix and is denoted by $A^H$. We can create matrix $A$ using .matrix in numpy.

In [55]:
A = np.matrix([[1,1j+1,0],[1j,3,-1],[4,7,0]]) 
print('A = ')
print(A)


A = 
[[ 1.+0.j  1.+1.j  0.+0.j]
 [ 0.+1.j  3.+0.j -1.+0.j]
 [ 4.+0.j  7.+0.j  0.+0.j]]


It is possible to convert matrix to n-dimensional array in python by numpy.asarray

In [56]:
A_array = np.asarray(A)
printArray(A_array)

	(1+0j)	(1+1j)	0j
	1j	(3+0j)	(-1+0j)
	(4+0j)	(7+0j)	0j



By doing this, hermitian of $A$ is calculated by $.H$

In [57]:
AH = A.H

In [58]:
print('AH = ')
printArray(np.asarray(AH))

AH = 
	(1-0j)	-1j	(4-0j)
	(1-1j)	(3-0j)	(7-0j)
	-0j	(-1-0j)	-0j



A Hermitian matrix $A$ satisfy $A = A^H$ 


$A^HA$ is a hermitian matrix.

In [59]:
AHA = np.matmul(A,AH)
print('AHA = ')
printArray(np.asarray(AHA))
print('Hermitian of AHA = ')
printArray(np.asarray(AHA.H))

AHA = 
	(3+0j)	(3+2j)	(11+7j)
	(3-2j)	(11+0j)	(21+4j)
	(11-7j)	(21-4j)	(65+0j)

Hermitian of AHA = 
	(3-0j)	(3+2j)	(11+7j)
	(3-2j)	(11-0j)	(21+4j)
	(11-7j)	(21-4j)	(65-0j)



 Note that $A^TA$ is a symmetric matrix.

In [60]:
ATA = np.matmul(A,A.T)
print('ATA = ')
printArray(np.asarray(ATA))

ATA = 
	(1+2j)	(3+4j)	(11+7j)
	(3+4j)	(9+0j)	(21+4j)
	(11+7j)	(21+4j)	(65+0j)



Let $U = I - 2\mathbf{u} \mathbf{u}^H$, where  $\mathbf{u}$ is the unit vector. Then $U = U^{-1}$

In [61]:
u = np.matrix([1,4+1j,8]).T
u = u / np.linalg.norm(u)
print('u = ')
printArray(np.asarray(u))
U = np.identity(3) - 2*(u@u.H)
print('U = ')
printArray(np.asarray(U))

u = 
	(0.11043152607484653+0j)
	(0.44172610429938614+0.11043152607484653j)
	(0.8834522085987723+0j)

U = 
	(0.975609756097561+0j)	(-0.09756097560975607+0.02439024390243902j)	(-0.19512195121951215+0j)
	(-0.09756097560975607-0.02439024390243902j)	(0.5853658536585367+0j)	(-0.7804878048780486-0.19512195121951215j)
	(-0.19512195121951215+0j)	(-0.7804878048780486+0.19512195121951215j)	(-0.5609756097560972+0j)



In [62]:
U_inv = np.linalg.inv(U)
printArray(np.asarray(U_inv))

	(0.9756097560975611+0j)	(-0.09756097560975611+0.02439024390243903j)	(-0.19512195121951223+0j)
	(-0.09756097560975614-0.024390243902439036j)	(0.5853658536585364+0j)	(-0.780487804878049-0.19512195121951226j)
	(-0.19512195121951226+0j)	(-0.7804878048780489+0.19512195121951223j)	(-0.5609756097560978+0j)



In [63]:
printArray(np.asarray(U@U))

	(0.9999999999999998+0j)	(-5.564324201348568e-17+1.214306433183765e-17j)	(-1.0408340855860843e-16+0j)
	(-5.564324201348568e-17-1.214306433183765e-17j)	(0.9999999999999998+0j)	(-3.896347848766276e-16-9.71445146547012e-17j)
	(-1.0408340855860843e-16+0j)	(-3.896347848766276e-16+9.71445146547012e-17j)	(0.9999999999999991+0j)



## 4 Rank
Rank of the matrix is found by following command.

In [64]:
np.linalg.matrix_rank(U)

3

In [65]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
printArray(A)

	1	2	3
	4	5	6
	7	8	9



In [66]:
np.linalg.matrix_rank(A)

2

Rank of a matrix and its reduced row echelon form are the same. Reduced row echelon form can be obtained by rref from sympy. You need to use .Matrix in syp

In [67]:
import sympy as syp
A = syp.Matrix([[1,2,3],[4,5,6],[7,8,9]])
A_rref = A.rref()
A_rref[0]

Matrix([
[1, 0, -1],
[0, 1,  2],
[0, 0,  0]])

The output of .rref is a tuple. The first element is the matrix in reduced row echelon from. The second element gives the row/rows which is/are not zero. 

In [68]:
A_rref[1]

(0, 1)

As you see, .Matrix in sympy is represented in a pretty format. For example:

In [69]:
A

Matrix([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

but,

In [70]:
print(A)

Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


You can still use printArray function.

In [71]:
printArray(np.asarray(A))

	1	2	3
	4	5	6
	7	8	9



## 5 Orthonormal basis
To construct an orthonormal basis for the range of a matrix use orth from scipy.linalg as follows:

In [72]:
from scipy.linalg import orth
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
orth_basis_A = orth(A)
printArray(orth_basis_A)

	-0.21483723836839663	0.8872306883463706
	-0.5205873894647373	0.2496439529882974
	-0.8263375405610782	-0.3879427823697744



Note that the rank of A is two and therefore, there are only two columns.
We can double the results by inner product of the columns. The results must be 0 if $i \neq j$ and 1 if $i = j$

In [73]:
print(orth_basis_A[:,0]@np.transpose([orth_basis_A[:,0]]))
print(orth_basis_A[:,0]@np.transpose([orth_basis_A[:,1]]))
print(orth_basis_A[:,1]@np.transpose([orth_basis_A[:,1]]))

[1.]
[-1.11022302e-16]
[1.]


Note that orth_basis[:,i] is 1D array in python. This means that orth_basis[:,i] is a row not a column. To get it work, you need to use <i>transpose</i> function from numpy and add square brackets([orth_basis[:,i]]) as shown above.


In [74]:
orth_basis_A[:,0]

array([-0.21483724, -0.52058739, -0.82633754])

In [75]:
orth_basis_A[:,0].T

array([-0.21483724, -0.52058739, -0.82633754])

In [76]:
np.transpose([orth_basis_A[:,0]])

array([[-0.21483724],
       [-0.52058739],
       [-0.82633754]])

Instead of matrix multiplication which is presented above, you can use <i>inner</i> function from numpy.

In [77]:
print(np.inner(orth_basis_A[:,0],orth_basis_A[:,0]))
print(np.inner(orth_basis_A[:,0],orth_basis_A[:,1]))
print(np.inner(orth_basis_A[:,1],orth_basis_A[:,1]))

1.0000000000000009
-1.1102230246251565e-16
1.0


## 6 Null space
Use <i>null_space</i> from <i>scipy.linalg</i> to construct an orthonormal basis for the null space.

In [78]:
from scipy.linalg import null_space
ns_A = null_space(A)
printArray(ns_A)

	-0.4082482904638631
	0.8164965809277263
	-0.4082482904638631



Note that in this case orthonormal basis for the range of $A$ are two vectors which define a plane in the space. The orthonormal basis of the null space is orthogonal to this plane. We can double check this by using inner product.

In [79]:
print(orth_basis_A[:,0]@ns_A)
print(orth_basis_A[:,1]@ns_A)

[5.55111512e-17]
[-5.82867088e-16]


## 7 Linearly independent
You can use rank to see if a set of vectors are independent or not. In case of $A = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}$, $ \text{rank}(A) = 2$ and therefore, 3 vectors in $A$ are dependent.

In [80]:
B = np.array([[0,4,1],[9,12,7],[4,2,21]])
np.linalg.matrix_rank(B)

3

You can also use determinant $\text{det}(A)$ to see whether a set of vectors are independent or not.

In [81]:
np.linalg.det(A)

0.0

In [82]:
np.linalg.det(B)

-674.0

If columns of A are linearly independent vectors, $N(A) = \{\pmb{0}\}$.

In [83]:
print('A = ')
printArray(A)
ns_A = null_space(A)
print('N(A) = ')
printArray(ns_A)
print('B = ')
printArray(B)
ns_B = null_space(B)
print('N(B) = ')
print(ns_B)

A = 
	1	2	3
	4	5	6
	7	8	9

N(A) = 
	-0.4082482904638631
	0.8164965809277263
	-0.4082482904638631

B = 
	0	4	1
	9	12	7
	4	2	21

N(B) = 
[]


Nullity is the dimension of the null space. The rank of $A$ plus the nullity of $A$ equals number of columns of $A$. In the given example, $\text{rank}(A) = 2$ and nullity of $A$ is $1$, the number of columns of $A$ is $2 + 1 = 3$. For B, $\text{rank}(B) = 3$ and nullity of $B$ is $0$. Number of columns is $3 + 0 = 3$

## 8 Orthogonal complement
Orthogonal complement of $R(A)$ is null space of $A^T$ which is $N(A^T) = R(A)^\perp$

In [84]:
ns_AT = null_space(A.T)
print('N(AT) = ')
printArray(ns_AT)

N(AT) = 
	-0.4082482904638629
	0.816496580927726
	-0.40824829046386296



In [85]:

print('inner product of A and N(AT) = ')
printArray(A@ns_AT)


inner product of A and N(AT) = 
	2.220446049250313e-16
	8.881784197001252e-16
	1.3322676295501878e-15



This means any linear combination of columns of $A$ is orthogonal to null space of $A^T$. Therefore,  $N(A^T) = R(A)^\perp$

## 9 Least squares solution
If A is an $m \times n$ matrix and its rank is n. $\hat{x} = (A^TA)^{-1}A^T\pmb{b}$  is the unique solution of $ A^TAx = A^T \pmb{b}$ and the least squares solution of  $ Ax = \pmb{b}$. This least squares solution is a unique solution.

Example:



\begin{cases}
      x_1 + x_2 = 2 \\
      -2x_1 + 4x_2 = -1\\
      x_1 + 2x_2 = 5
\end{cases}


$
\begin{bmatrix}
1 & -2 & 1\\
1 & 4 & -1
\end{bmatrix}
\begin{bmatrix}
1 & 1\\
-2 & 4\\
1 & 2
\end{bmatrix}  \begin{bmatrix}x_1\\x_2\end{bmatrix} = \begin{bmatrix}
1 & -2 & 1\\
1 & 4 & -1
\end{bmatrix} \begin{bmatrix}2\\-1\\5\end{bmatrix}
$




In [112]:
A = np.matrix([[1,1],[-2,4],[1,-1]])
b = np.matrix([2,-1,5]).T

In [113]:
x = np.linalg.inv(A.T@A)@(A.T@b)


In [114]:
x

matrix([[2.40909091],
        [0.68181818]])

In [117]:
A

matrix([[ 1,  1],
        [-2,  4],
        [ 1, -1]])