# Linear Algebra, Advanced Concepts
This note-book is devoted to teaching how to use python for advanced concepts in linear algebra. Step by step you see how to use different functions in python to do computation in linear algebra.

## 1 Singular value decompisition

Use svd from .linalg to perform singular value decompisition. Let

$A = \begin{bmatrix}
1 & 7 & 2\\
4 & 0 & 9\\
5 & 8 & 2
\end{bmatrix}$

We can create $A$ as follows:

In [208]:
import numpy as np
A = np.array([[1,7,2],[4,0,9],[5,8,2]])
print(A)


[[1 7 2]
 [4 0 9]
 [5 8 2]]


As you see the print function in python cannot print this 2D-array in a pretty format. To solve this issue, we can create following function for printing matrices.

In [209]:
def printArray(A):
    if A.ndim > 1:
        for matrix_row in A:
            s = ''
            for element in matrix_row:
               
                s = s + '\t' + str(element)
            print(s)
            
    elif A.ndim == 1:
        s = ''
        for element in A:
            s = s + '\t' + str(element)
        print(s)
    print('')

In [210]:
printArray(A)

	1	7	2
	4	0	9
	5	8	2



Singular value decompostion of $A$ is $A = U\Sigma V^T$
we can use svd() in .linalg to do singular value decomposition in python

In [211]:
(U,S,VT) = np.linalg.svd(A)
print('U = ')
printArray(U)
print('S = ')
printArray(S)
print('VT = ')
printArray(VT)

U = 
	0.4955490212302891	-0.36519550871464956	-0.788075762837781
	0.5233789676437401	0.8496460787338146	-0.06462195540546112
	0.6931851295187129	-0.38043893242792737	0.612176931047899

S = 
	12.967612725738011	8.398154610072645	2.3047818422993984

VT = 
	0.46693178362590376	0.6951413784026855	0.5465831807441089
	0.13469556070380387	-0.6667988719461702	0.7329640989148127
	0.8739747223842462	-0.2686219060384506	-0.40498204432993057



Note that S computed by svd only contains the sigular values of S which are the diagonal elements $\Sigma$. $\Sigma$ is computed as follows

In [212]:
Sigma = np.diag(S)
printArray(Sigma)

	12.967612725738011	0.0	0.0
	0.0	8.398154610072645	0.0
	0.0	0.0	2.3047818422993984



We can see that the singular value decompisition is computed correctly by following command. 

In [213]:
diff = A - np.matmul(U,np.matmul(Sigma,VT))
print(np.max(np.abs(diff)))

6.168200105464311e-15


Determinat of the matrix have the following relationship with its singular values.
$\text{det}(A) = \sigma_1\cdot\sigma_2\cdot\sigma_3 \ldots \sigma_n$. We can show this as follows:

In [214]:
det_A = np.linalg.det(A)
print('det(A) = ', det_A)
singular_values_multiplications = np.prod(S)
print('singular values multiplications = ', singular_values_multiplications)

det(A) =  250.9999999999999
singular values multiplications =  250.99999999999972


## 2 Eigen values and Eigen vectors

Eigenvalues and eigen vectors of $A$ are computed by $\text{eig()}$ function from .linalg

In [215]:
(l,V) = np.linalg.eig(A)
print('eigen values = ')
printArray(l)
print('eigen vectors = ')
printArray(V)

eigen values = 
	12.889603103961992	-2.7136575578172217	-7.1759455461447645

eigen vectors = 
	-0.4628165201727251	-0.8798030708949003	0.5577205496916918
	-0.5995421343373721	0.3885030095494413	-0.7518744720388498
	-0.6529548972244545	0.2738831283867805	0.3516142300133738



Determinat of the matrix have the following relationship with its eigen values.
$\text{det}(A) = \lambda_1\cdot\lambda_2\cdot\lambda_3 \ldots \lambda_n$. We can show this as follows:

In [216]:
det_A = np.linalg.det(A)
print('det(A) = ', det_A)
eigen_values_multiplications = np.prod(l)
print('eigen values multiplications = ',eigen_values_multiplications)

det(A) =  250.9999999999999
eigen values multiplications =  250.99999999999983


We can also shows that roots squares of eigenvalues of $A^TA$(we can denote it by $\lambda$) are equal to singular values of $A$ (denoted by $\sigma$). $i.e. \sigma = \sqrt{\lambda}$

In [217]:
ATA = np.matmul(A.T,A)
(l_ATA,V) = np.linalg.eig(ATA)
print('root square of lambdas = ')
printArray(np.sqrt(l_ATA))
print('sigmas = ')
printArray(S)

root square of lambdas = 
	12.967612725738018	2.3047818422993998	8.398154610072647

sigmas = 
	12.967612725738011	8.398154610072645	2.3047818422993984



## 3 Complex matrix and Hermitian

Matrix A can have complex entries. For example:

$A = \begin{bmatrix}
1 & i+1 & 0\\
i & 3 & -1\\
4 & 7 & 0
\end{bmatrix}$  

Hermitian of A is conjugate transpose of the matrix and is denoted by $A^H$. We can create matrix $A$ using .matrix in numpy.

In [218]:
A = np.matrix([[1,1j+1,0],[1j,3,-1],[4,7,0]]) 
print('A = ')
print(A)


A = 
[[ 1.+0.j  1.+1.j  0.+0.j]
 [ 0.+1.j  3.+0.j -1.+0.j]
 [ 4.+0.j  7.+0.j  0.+0.j]]


It is possible to convert matrix to n-dimensional array in python by numpy.asarray

In [219]:
A_array = np.asarray(A)
printArray(A_array)

	(1+0j)	(1+1j)	0j
	1j	(3+0j)	(-1+0j)
	(4+0j)	(7+0j)	0j



By doing this, hermitian of $A$ is calculated by $.H$

In [220]:
AH = A.H

In [221]:
print('AH = ')
printArray(np.asarray(AH))

AH = 
	(1-0j)	-1j	(4-0j)
	(1-1j)	(3-0j)	(7-0j)
	-0j	(-1-0j)	-0j



A Hermitian matrix $A$ satisfy $A = A^H$ 


$A^HA$ is a hermitian matrix.

In [222]:
AHA = np.matmul(A,AH)
print('AHA = ')
printArray(np.asarray(AHA))
print('Hermitian of AHA = ')
printArray(np.asarray(AHA.H))

AHA = 
	(3+0j)	(3+2j)	(11+7j)
	(3-2j)	(11+0j)	(21+4j)
	(11-7j)	(21-4j)	(65+0j)

Hermitian of AHA = 
	(3-0j)	(3+2j)	(11+7j)
	(3-2j)	(11-0j)	(21+4j)
	(11-7j)	(21-4j)	(65-0j)



 Note that $A^TA$ is a symmetric matrix.

In [223]:
ATA = np.matmul(A,A.T)
print('ATA = ')
printArray(np.asarray(ATA))

ATA = 
	(1+2j)	(3+4j)	(11+7j)
	(3+4j)	(9+0j)	(21+4j)
	(11+7j)	(21+4j)	(65+0j)



Let $U = I - 2\mathbf{u} \mathbf{u}^H$, where  $\mathbf{u}$ is the unit vector. Then $U = U^{-1}$

In [224]:
u = np.matrix([1,4+1j,8]).T
u = u / np.linalg.norm(u)
print('u = ')
printArray(np.asarray(u))
U = np.identity(3) - 2*(u@u.H)
print('U = ')
printArray(np.asarray(U))

u = 
	(0.11043152607484653+0j)
	(0.44172610429938614+0.11043152607484653j)
	(0.8834522085987723+0j)

U = 
	(0.975609756097561+0j)	(-0.09756097560975607+0.02439024390243902j)	(-0.19512195121951215+0j)
	(-0.09756097560975607-0.02439024390243902j)	(0.5853658536585367+0j)	(-0.7804878048780486-0.19512195121951215j)
	(-0.19512195121951215+0j)	(-0.7804878048780486+0.19512195121951215j)	(-0.5609756097560972+0j)



In [225]:
U_inv = np.linalg.inv(U)
printArray(np.asarray(U_inv))

	(0.9756097560975611+0j)	(-0.09756097560975611+0.02439024390243903j)	(-0.19512195121951223+0j)
	(-0.09756097560975614-0.024390243902439036j)	(0.5853658536585364+0j)	(-0.780487804878049-0.19512195121951226j)
	(-0.19512195121951226+0j)	(-0.7804878048780489+0.19512195121951223j)	(-0.5609756097560978+0j)



In [226]:
printArray(np.asarray(U@U))

	(0.9999999999999998+0j)	(-5.564324201348568e-17+1.214306433183765e-17j)	(-1.0408340855860843e-16+0j)
	(-5.564324201348568e-17-1.214306433183765e-17j)	(0.9999999999999998+0j)	(-3.896347848766276e-16-9.71445146547012e-17j)
	(-1.0408340855860843e-16+0j)	(-3.896347848766276e-16+9.71445146547012e-17j)	(0.9999999999999991+0j)



## 4 Rank
Rank of the matrix is found by following command.

In [227]:
np.linalg.matrix_rank(U)

3

In [228]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
printArray(A)

	1	2	3
	4	5	6
	7	8	9



In [229]:
np.linalg.matrix_rank(A)

2

Rank of a matrix and its reduced row echelon form are the same. Reduced row echelon form can be obtained by rref from sympy. You need to use .Matrix in syp

In [230]:
import sympy as syp
A = syp.Matrix([[1,2,3],[4,5,6],[7,8,9]])
A_rref = A.rref()
A_rref[0]

Matrix([
[1, 0, -1],
[0, 1,  2],
[0, 0,  0]])

The output of .rref is a tuple. The first element is the matrix in reduced row echelon from. The second element gives the row/rows which is/are not zero. 

In [231]:
A_rref[1]

(0, 1)

As you see, .Matrix in sympy is represented in a pretty format. For example:

In [232]:
A

Matrix([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

but,

In [233]:
print(A)

Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


You can still use printArray function.

In [234]:
printArray(np.asarray(A))

	1	2	3
	4	5	6
	7	8	9



To construct an orthonormal basis for the range of a matrix use orth from scipy.linalg as follows:

In [235]:
from scipy.linalg import orth
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
orth_basis = orth(A)
printArray(orth_basis)

	-0.21483723836839663	0.8872306883463706
	-0.5205873894647373	0.2496439529882974
	-0.8263375405610782	-0.3879427823697744



Note that the rank of A is two and therefore, there are only two column.