Use svd from .linalg to perform singular value decompisition

In [1]:
import numpy as np

In [3]:
A = np.array([[1,7,2],[4,0,9],[5,8,2]])
print(A)

[[1 7 2]
 [4 0 9]
 [5 8 2]]


In [8]:
(U,S,VT) = np.linalg.svd(A)
print('U = ',U)
print('S = ',S)
print('VT = ',VT)

U =  [[ 0.49554902 -0.36519551 -0.78807576]
 [ 0.52337897  0.84964608 -0.06462196]
 [ 0.69318513 -0.38043893  0.61217693]]
S =  [12.96761273  8.39815461  2.30478184]
VT =  [[ 0.46693178  0.69514138  0.54658318]
 [ 0.13469556 -0.66679887  0.7329641 ]
 [ 0.87397472 -0.26862191 -0.40498204]]


We can check if $A = U\Sigma V^T$. note that S computed by svd only contains only the sigular values of S which are the diagonal elements $\Sigma$. $\Sigma$ is computed as follows

In [16]:
Sigma = np.diag(S)
print(Sigma)

[[12.96761273  0.          0.        ]
 [ 0.          8.39815461  0.        ]
 [ 0.          0.          2.30478184]]


In [17]:
A - np.matmul(U,np.matmul(Sigma,VT)) 

array([[-1.11022302e-15,  2.66453526e-15,  2.44249065e-15],
       [ 1.33226763e-15,  6.16820011e-15,  0.00000000e+00],
       [-8.88178420e-16,  1.77635684e-15,  1.77635684e-15]])

Determinat of the matrix have the following relationship with its singular values.
$\text{det}(A) = \sigma_1\cdot\sigma_2\cdot\sigma_3 \ldots \sigma_n$. We can show this as follows:

In [23]:
det_A = np.linalg.det(A)
print('det(A) = ', det_A)
singular_values_multiplications = np.prod(S)
print('singular values multiplications = ', singular_values_multiplications)

det(A) =  250.9999999999999
singular values multiplications =  250.99999999999972


Eigenvalues and eigen vectors of $A$ are computed by $\text{eig()}$ function from .linalg

In [30]:
(l,V) = np.linalg.eig(A)
print(l)
print(V)

[12.8896031  -2.71365756 -7.17594555]
[[-0.46281652 -0.87980307  0.55772055]
 [-0.59954213  0.38850301 -0.75187447]
 [-0.6529549   0.27388313  0.35161423]]


Determinat of the matrix have the following relationship with its eigen values.
$\text{det}(A) = \lambda_1\cdot\lambda_2\cdot\lambda_3 \ldots \lambda_n$. We can show this as follows:

In [31]:
det_A = np.linalg.det(A)
print('det(A) = ', det_A)
eigen_values_multiplications = np.prod(l)
print('eigen values multiplications = ',eigen_values_multiplications)

det(A) =  250.9999999999999
eigen values multiplications =  250.99999999999983


We can also shows that roots squares of eigenvalues of $A^TA$(we can denote it by $\lambda$) are equal to singular values of $A$ (denoted by $\sigma$). $i.e. \sigma = \sqrt{\lambda}$

In [40]:
ATA = np.matmul(A.T,A)
(l_ATA,V) = np.linalg.eig(ATA)
print('root square of lambdas', np.sqrt(l_ATA))
print('sigmas = ', S)

root square of lambdas [12.96761273  2.30478184  8.39815461]
sigmas =  [12.96761273  8.39815461  2.30478184]
