The goal of this notebook is to teach how to use numpy for solving basic linear algebra problems. Start with creating a matrix.

$A = \begin{bmatrix}
1 & 2 & 6\\
4 & 7 & 6\\
1 & 8 & 3
\end{bmatrix}$

In [9]:
import numpy as np
A = np.array([[1,2,6],[4,7,6],[1,8,3]])
print(A)

[[1 2 6]
 [4 7 6]
 [1 8 3]]


As you see the print function in python cannot print this 2D-array in a pretty format. To solve this issue, we can create following function for printing matrices.

In [10]:
def printArray(A):
    if A.ndim > 1:
        for matrix_row in A:
            s = ''
            for element in matrix_row:
               
                s = s + '\t' + str(element)
            print(s)
            
    elif A.ndim == 1:
        s = ''
        for element in A:
            s = s + '\t' + str(element)
        print(s)
    print('')

In [11]:
printArray(A)

	1	2	6
	4	7	6
	1	8	3



The transpose of A is A.T

In [12]:
B = A.T
printArray(B)

	1	4	1
	2	7	8
	6	6	3



matmul is used to calculate matrix multiplication.

In [16]:
C = np.matmul(A,B)
printArray(C)

	41	54	35
	54	101	78
	35	78	74



Another approach to do matrix multiplication is to use @ operator

In [18]:
C2 = A@B
printArray(C)

	41	54	35
	54	101	78
	35	78	74



Determinant of a matrix is computed by det()

In [19]:
a = np.linalg.det(C)
a

12320.999999999995

To calculate inverse, simply use inv from linalg in numpy.



In [20]:
D = np.linalg.inv(C)
printArray(D)

	0.11281551822092367	-0.10275140004869736	0.0549468387306225
	-0.10275140004869739	0.14682249817384957	-0.10616021426832238
	0.05494683873062254	-0.10616021426832241	0.09942374807239673



$C^{-1}C$ is equal to identity matrix, we can check this as follows

In [6]:
np.matmul(D,C)

array([[ 1.00000000e+00,  2.35922393e-16, -8.46545056e-16],
       [ 4.30211422e-16,  1.00000000e+00,  2.02615702e-15],
       [-4.44089210e-16, -8.88178420e-16,  1.00000000e+00]])