The goal of this notebook is to teach how to use numpy for solving basic linear algebra problems. Start with creating a matrix.

In [41]:
import numpy as np
A = np.array([[1,2,6],[4,7,6],[1,8,3]])
print(A)

[[1 2 6]
 [4 7 6]
 [1 8 3]]


The transpose of A is A.T

In [42]:
B = A.T
print(B)

[[1 4 1]
 [2 7 8]
 [6 6 3]]


matmul is used to calculate matrix multiplication.

In [43]:
C = np.matmul(A,B)
print(C)

[[ 41  54  35]
 [ 54 101  78]
 [ 35  78  74]]


Determinant of a matrix is computed by det()

In [47]:
a = np.linalg.det(C)
a

12320.999999999995

To calculate inverse, simply use inv from linalg in numpy.



In [49]:
D = np.linalg.inv(C)
print(D)

[[ 0.11281552 -0.1027514   0.05494684]
 [-0.1027514   0.1468225  -0.10616021]
 [ 0.05494684 -0.10616021  0.09942375]]


$C^{-1}C$ is equal to identity matrix, we can check this as follows

In [51]:
np.matmul(D,C)

array([[ 1.00000000e+00,  2.35922393e-16, -8.46545056e-16],
       [ 4.30211422e-16,  1.00000000e+00,  2.02615702e-15],
       [-4.44089210e-16, -8.88178420e-16,  1.00000000e+00]])