The goal of this notebook is to teach how to use numpy for solving linear algebra problems. Start with creating a matrix.

In [13]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

The transpose of A is A.T

In [21]:
B = A.T
print(B)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


matmul is used to calculate matrix multiplication.

In [22]:
C = np.matmul(A,B)
print(C)

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]
